name: CI Maven-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Eisar1#?732
          POSTGRES_PORT: 5432
          POSTGRES_DB: quickplan
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Eclipse Temurin JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
        cache: maven
    - name: Build Project
      run: mvn -B install --file ./pom.xml
