name: CI Maven-Build, -Test & Docker-Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build & Test:
    runs-on: ubuntu-latest
    services:
      # Description for runner-local postgres-server
      postgres:
        image: postgres
        env:
          # Values based on "src/main/resources/application.properties"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Eisar1#?732
          POSTGRES_PORT: 5432
          POSTGRES_DB: quickplan
        # Options to make the runner wait until the docker container is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # Forward Docker's port 5432 to the host's port 5432
        ports:
          - 5432:5432
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Eclipse Temurin JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"
        cache: maven
    - name: Build Project
      run: mvn -B install --file ./pom.xml
  
  # Release:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Check out repository
  #     uses: actions/checkout@v4
  #   - name: 
